SIM ?= verilator
TOPLEVEL_LANG ?= verilog
VERILOG_SOURCES += $(PWD)/../../../srcs/rtl/types.sv
VERILOG_SOURCES += $(PWD)/../../../srcs/rtl/mulop_decoder.sv

TOPLEVEL = mulop_decoder

MODULE = tests

include $(shell cocotb-config --makefiles)/Makefile.sim