SIM ?= verilator
TOPLEVEL_LANG ?= verilog
VERILOG_SOURCES += $(PWD)/../../../srcs/rtl/data_align_unit.sv

TOPLEVEL = data_align_unit

MODULE = tests

include $(shell cocotb-config --makefiles)/Makefile.sim