SIM ?= verilator
TOPLEVEL_LANG ?= verilog
VERILOG_SOURCES += $(PWD)/../../../srcs/rtl/types.sv
VERILOG_SOURCES += $(PWD)/../../../srcs/rtl/branch_unit.sv

TOPLEVEL = branch_unit

MODULE = tests

include $(shell cocotb-config --makefiles)/Makefile.sim