SIM ?= verilator
TOPLEVEL_LANG ?= verilog
VERILOG_SOURCES += $(PWD)/../../../srcs/rtl/types.sv
VERILOG_SOURCES += $(PWD)/../../../srcs/rtl/arithop_decoder.sv

TOPLEVEL = arithop_decoder

MODULE = tests

include $(shell cocotb-config --makefiles)/Makefile.sim