SIM ?= verilator
TOPLEVEL_LANG ?= verilog
VERILOG_SOURCES += $(PWD)/../../../srcs/rtl/types.sv
VERILOG_SOURCES += $(PWD)/../../../srcs/rtl/write_mask_unit.sv

TOPLEVEL = write_mask_unit

MODULE = tests

include $(shell cocotb-config --makefiles)/Makefile.sim