SIM ?= verilator
TOPLEVEL_LANG ?= verilog
VERILOG_SOURCES += $(PWD)/../../../srcs/rtl/types.sv
VERILOG_SOURCES += $(PWD)/../../../srcs/rtl/sign_extend_unit.sv

TOPLEVEL = sign_extend_unit

MODULE = tests

include $(shell cocotb-config --makefiles)/Makefile.sim