SIM ?= verilator
TOPLEVEL_LANG ?= verilog
VERILOG_SOURCES += $(PWD)/../../../srcs/rtl/types.sv
VERILOG_SOURCES += $(PWD)/../../../srcs/rtl/logicop_decoder.sv

TOPLEVEL = logicop_decoder

MODULE = tests

include $(shell cocotb-config --makefiles)/Makefile.sim